### ISSUE TITLE
Timer is running slow

### ISSUE THREAD

**Issue by hjelmeir** [UnicornAgency/Trax#39]
I started a timer in Toggl and one in Trax. Toggle time: 3:14, trax time: 1:45.
Did the same with my stopwatch on my phone:
- phone: 53 secs
- Trax: 40 secs

I tested this on both by running 'yarn dev' and by using the application build

**Comment by thinkclay** [comment]
Ohh that is a big bug. Thanks for letting me know.

**Comment by thinkclay** [comment]
@hjelmeir can you download the v0.5.1 build in [releases](/releases) and see if this resolves. I have near perfect timing on my computer with this version, but there could be issues if CPU is busy or running slow. I want to make sure that's not an issue moving forward.

**Comment by hjelmeir** [comment]
@thinkclay It still runs a little slow for me. My CPU is pretty busy (old computer) so it gets overwhelmed pretty easy. I was running xCode simulators, which just makes my computer crawl.
toggle: 10min 11secs
phone timer: 10min 32 secs
