### ISSUE TITLE
Installation instructions are not clear

### ISSUE THREAD

**Issue by hjelmeir** [UnicornAgency/Trax#46]
There are a lot of missing pieces in the installation instructions.

- person will need `graphql-cli` installed
- how to set up the oauth app properly: what should the url's be?
- what settings are important for the Personal Access Token
- after doing yarn electron:build, how to copy the application file out into my applications (Matt had to help me with that) 
- etc

**Comment by thinkclay** [comment]
Updated the Readme to reflect current stack. Relay, oauth and the other things you mentioned are no longer relevant. Getting up and running with development is much less involved now, and releases are published under the [releases](/releases) page. Thanks for bring this to my attention. Closing out the issue.
