### ISSUE TITLE
Research and make a list of domains for the app

### ISSUE THREAD

**Issue by thinkclay** [UnicornAgency/Trax#48]
Something concise and memorable.. like `gettrax.com` or `trax.io` etc. Use 101domain to search for available domains and make a list of at least 10 domains here for us to pick one.

**Comment by mattirizarry** [comment]
gettrax.app - 19.99
gettrax.io - 29.99 (59.99 renewal)
justtrax.it - 14.99
keeptrax.app - 19.99
traxit.app - 19.99
getontrax.com - 7.99 (13.49 renewal)
getontrax.io - 29.99 (59.99 renewal)
getontrax.app - 19.99
ontrax.app - 19.99
traxapp.it - 14.99
keeptrax.info - 2.99 (16.99 renewal)
yourtrax.io - 29.99 (59.99 renewal)
yourtrax.app - 19.99
traxtime.io - 29.99 (59.99 renewal)
traxtime.app - 19.99
