### ISSUE TITLE
Look into WP themes on Themeforest.net

### ISSUE THREAD

**Issue by thinkclay** [UnicornAgency/Trax#49]
We want to build the public site on Wordpress. Pickup out the top themes that you think match the brand/aesthetics/etc. Provide maybe a list of your three favorites here.

**Comment by mattirizarry** [comment]
#### [TheGem - $59](https://themeforest.net/item/thegem-creative-multipurpose-highperformance-wordpress-theme/16061685)
#### [Fenix - $59](https://themeforest.net/item/fenix-responsive-multipurpose-wordpress-theme/19923654)
#### [Landium - $44](https://themeforest.net/item/landium-app-landing-page-wordpress-theme-pack/18914504)
#### [Appstar - $39](https://themeforest.net/item/appstar-responsive-wordpress-app-landing-theme/19597040)

**Comment by thinkclay** [comment]
@mattirizarry I grabbed "TheGem" theme and uploaded to Team Drive > TRX > Design > [Public Site](https://drive.google.com/drive/u/1/folders/1wUspdtX5sMAxSL4r18gIMhuya7ILzomC). Go ahead and pull that down and start setting up whichever layout/design you like best ;)
