### ISSUE TITLE
Step 1: Lets find a markdown package for Go that has a rich AST

### ISSUE THREAD

**Issue by thinkclay** [UnicornAgency/Trax#7]
We want to be able to not only distinguish between typical markdown, but also specifically custom code tags or language types. 

# Completion Criteria

- [ ] Can parse typical markdown
- [ ] Can parse and distinguish a three backtick code block
- [ ] Can parse a code block as language type (e.g.: `TRAX` vs `javascript`)

See [github's markdown spec](https://github.github.com/gfm/#example-111) for details of what we're looking for with the AST.

**Comment by mrosentr** [comment]
Go has built in AST support with this package:
https://golang.org/pkg/go/ast/
